// Mocks generated by Mockito 5.3.2 from annotations
// in invoices_tdd/test/features/invoice/presentation/invoices_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:invoices_tdd/core/error/failure.dart' as _i6;
import 'package:invoices_tdd/core/usecases/use_case.dart' as _i9;
import 'package:invoices_tdd/core/util/input_converter.dart' as _i10;
import 'package:invoices_tdd/features/invoice/domain/entities/invoice.dart'
    as _i7;
import 'package:invoices_tdd/features/invoice/domain/repositories/invoice_repository.dart'
    as _i2;
import 'package:invoices_tdd/features/invoice/domain/usecases/get_all_invoices.dart'
    as _i8;
import 'package:invoices_tdd/features/invoice/domain/usecases/get_concrete_invoice.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInvoiceRepository_0 extends _i1.SmartFake
    implements _i2.InvoiceRepository {
  _FakeInvoiceRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetConcreteInvoice].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcreteInvoice extends _i1.Mock
    implements _i4.GetConcreteInvoice {
  MockGetConcreteInvoice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InvoiceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInvoiceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InvoiceRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Invoice>?> call(_i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Invoice>?>.value(),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Invoice>?>);
}

/// A class which mocks [GetAllInvoices].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllInvoices extends _i1.Mock implements _i8.GetAllInvoices {
  MockGetAllInvoices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InvoiceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInvoiceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InvoiceRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Invoice>>?> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Invoice>>?>.value(),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Invoice>>?>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i10.InputConverter {
  MockInputConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Either<_i6.Failure, String> inputToString(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #inputToString,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #inputToString,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, String>);
}
